Fixes an issue with lifecycle adapter when using lifecycle-runtime 2.3. (#57)
Description
Fixes a crash with lifecycle adapter when using lifecycle-runtime 2.3:

java.lang.IllegalStateException: no event up from DESTROYED

Since 2.3 ON_DESTROY became a terminal event and we can no longer emit any other events after that.
We're now creating a new lifecycle registry once we have emitted a ON_DESTROY.

How Has This Been Tested?
 All features has been added/updated in sample application ( /sample )
This was tested when updating to lifecycle-runtime 2.3 in the sample.